name: Build and deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@v6
        with:
          node-version: "24.16.0"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ⚙️ Generate release infos
        id: release
        run: |
          echo "release_tag=$(echo ${{ github.event.head_commit.message }} | grep -o 'v\(.*\)')" >> $GITHUB_OUTPUT
      - name: 🔖 Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.release.outputs.release_tag }}
          name: ${{ steps.release.outputs.release_tag }}
          generate_release_notes: true
