name: Build and deploy

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-node@v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm publish --provenance --access public
      - name: ⚙️ Generate release infos
        id: release
        run: |
          echo "release_tag=$(echo ${{ github.event.head_commit.message }} | grep -o 'v\(.*\)')" >> $GITHUB_OUTPUT
      - name: 🔖 Release
        uses: softprops/action-gh-release@v3.0.1
        with:
          tag_name: ${{ steps.release.outputs.release_tag }}
          name: ${{ steps.release.outputs.release_tag }}
          generate_release_notes: true
